apiVersion: apps/v1
kind: Deployment
metadata:
  name: hau2
  namespace: hau  # or the appropriate namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hau2
  template:
    metadata:
      labels:
        app: hau2
    spec:
      containers:
      - name: hau2
        image: necsorte/nullhau:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-registry-secret
